export enum MaterialIcon {
  Work = "work",
  Action_Key = "action_key",
  Event = "event",
  Balance = "balance",
  Work_Update = "work_update",
  Map = "map",
  Flag = "flag",
  Location_City = "location_city",
  Location_On = "location_on",
  Person = "person",
  Mail = "mail",
  Lock = "lock",
  Close = "close",
  Edit = "edit",
}
